### ISSUE TITLE
Collaborate admin view broken

### ISSUE THREAD

**Issue by BillMills** [mozillascience/site#27]
Visiting the admin view for Collaborate returns:

```
TypeError: /app/views/collaborate/admin.jade:38
   36|                 a(href='/projects/' + project.slug)=project.title
   37|               td
 > 38|                 each l, ind in project.lead
   39|                   a(href='/u/' + l.username)=l.name
   40|                   if ind != project.lead.length-1
   41|                     | ,&nbsp;

Cannot read property 'length' of null
   at jade_debug.unshift.lineno (eval at <anonymous> (/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1243:31)
   at jade_debug.unshift.lineno (eval at <anonymous> (/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1294:4)
   at eval (eval at <anonymous> (/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1532:4)
   at eval (eval at <anonymous> (/app/node_modules/jade/lib/index.js:218:8), <anonymous>:1553:22)
   at res (/app/node_modules/jade/lib/index.js:219:38)
   at Object.exports.renderFile (/app/node_modules/jade/lib/index.js:380:38)
   at View.exports.renderFile [as engine] (/app/node_modules/jade/lib/index.js:370:21)
   at View.render (/app/node_modules/express/lib/view.js:76:8)
   at Function.app.render (/app/node_modules/express/lib/application.js:527:10)
   at ServerResponse.res.render (/app/node_modules/express/lib/response.js:900:7)
   at EventEmitter.<anonymous> (/app/routes/projects.js:71:13)
   at EventEmitter.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
   at EventEmitter.emit (events.js:95:17)
   at Promise.safeEmit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
   at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
   at /app/node_modules/mongoose/lib/query.js:1902:26 
```

**Comment by acabunoc** [comment]
oops, try now!

**Comment by BillMills** [comment]
Awesome, looks good :)

**Comment by acabunoc** [comment]
I will add better db checks one day
